# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aaebc80d395cf1332d9e4527eb0ac52af7cf6a39876883a8d933628d6afdd6001f0676643717bb07055032ac3e305f3b70ba5f266c3677adee9a4e61c60cdfd

test:
  secret_key_base: 3aa520e5692167ec984865fd3604a29fb818ce5c232e61b34f4857ced2eaf7c2044fab00a60c93f4858b55690dc92567ddbc727fb0a82ba94a660b082abff3e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
